name: TransferPlugin
version: '1.2'
main: de.hackv0gel.transferPlugin.TransferPlugin
load: STARTUP
authors: [ HackV0gel ]
description: BungeeCord Alternate
website: https://github.com/PublicCode1337
api-version: 1.21
commands:
  server:
    description: Transfer a player to another server
    usage: /server <server>
  bungee:
    description: Displays information about V0gelCord
    usage: /bungee